openapi: 3.0.0

info:
  title: E-Commerce Backend API
  description: Production ready E-commerce backend using Node.js, Express, MongoDB, JWT, Cloudinary
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local server

tags:
  - name: Auth
  - name: Products
  - name: Categories
  - name: Cart
  - name: Orders
  - name: Payment
  - name: Wishlist
  - name: Admin

paths:

  /auth/register:
    post:
      tags: [Auth]
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        201:
          description: User registered successfully

  /auth/login:
    post:
      tags: [Auth]
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: User logged in

  /auth/logout:
    post:
      tags: [Auth]
      summary: User logout
      responses:
        200:
          description: User logged out

  /products:
    get:
      tags: [Products]
      summary: Retrieves a list of all products
      responses:
        200:
          description: Products fetched

    post:
      tags: [Products]
      summary: Creates a new product (admin only)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        201:
          description: Product created

  /products/{id}:
    get:
      tags: [Products]
      summary: Retrieves details of a specific product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Product details fetched

    post:
      tags: [Products]
      summary: Updates an existing product by ID (admin only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Product updated

  /products/{id}/delete:
    post:
      tags: [Products]
      summary: Deletes a product by ID (admin only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Product deleted

  /products/search:
    get:
      tags: [Products]
      summary: Allows users to search for products by name, category, or other criteria
      responses:
        200:
          description: Search results

  /products/review:
    post:
      tags: [Products]
      summary: Allows users to leave a review for a product they've purchased
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        201:
          description: Review added

  /products/{id}/reviews:
    get:
      tags: [Products]
      summary: Retrieves all reviews for a specific product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Reviews fetched

  /cart:
    get:
      tags: [Cart]
      summary: Retrieves the user's cart
      responses:
        200:
          description: Cart fetched

    post:
      tags: [Cart]
      summary: Adds a product to the user's cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Product added to cart

  /cart/remove:
    post:
      tags: [Cart]
      summary: Removes a product from the user's cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Product removed from cart

  /order:
    post:
      tags: [Orders]
      summary: Creates a new order
      responses:
        201:
          description: Order created

  /orders:
    get:
      tags: [Orders]
      summary: Retrieves a list of the user's orders
      responses:
        200:
          description: Orders fetched

  /order/{id}/cancel:
    post:
      tags: [Orders]
      summary: Allows users to cancel an order before it’s processed
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Order cancelled

  /order/{id}/return:
    post:
      tags: [Orders]
      summary: Allows users to initiate a return for an order they’ve received
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return initiated

  /order/{id}/invoice:
    get:
      tags: [Orders]
      summary: Generates and retrieves the invoice for a specific order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Invoice generated

  /payment:
    post:
      tags: [Payment]
      summary: Processes a payment for an order
      responses:
        200:
          description: Payment successful

  /wishlist:
    get:
      tags: [Wishlist]
      summary: Retrieves all products in the user's wishlist
      responses:
        200:
          description: Wishlist fetched

  /wishlist/add:
    post:
      tags: [Wishlist]
      summary: Adds a product to the user's wishlist
      responses:
        200:
          description: Product added to wishlist

  /wishlist/remove:
    post:
      tags: [Wishlist]
      summary: Removes a product from the user's wishlist
      responses:
        200:
          description: Product removed from wishlist

  /admin/dashboard:
    get:
      tags: [Admin]
      summary: Provides an overview of key metrics for the admin
      responses:
        200:
          description: Dashboard data

  /admin/orders:
    get:
      tags: [Admin]
      summary: Allows the admin to view all orders
      responses:
        200:
          description: Orders fetched
